language: android
dist: trusty
jdk:
- openjdk8
android:
  components:
  - tools
  - build-tools-28.0.3
  - android-28
install:
  - echo y | sdkmanager "cmake;3.6.4111459"
  - echo y | sdkmanager "lldb;3.1"
before_script:
  - export NDK=$ANDROID_HOME/ndk-bundle
  - export NINJA_PATH=/usr/bin/ninja
script:
- "cd $TRAVIS_BUILD_DIR"
- "cd TMessagesProj/jni"
- "./build_ffmpeg_clang.sh"
- "./patch_boringssl.sh"
- "./build_boringssl.sh"
- "cd ../.."
- "./gradlew assembleAfatRelease"
before_install:
- sudo apt-get install ninja build-essential
