language: android
dist: trusty
jdk:
  - openjdk8
android:
  components:
    - build-tools-28.0.3
    - android-28
addons:
  apt_packages:
    - ninja-build

install:
  - echo y | sdkmanager "ndk-bundle" >/dev/null
  - echo y | sdkmanager "cmake;3.6.4111459" >/dev/null
  - echo y | sdkmanager "lldb;3.1" >/dev/null
before_script:
  - export NDK=$ANDROID_HOME/ndk-bundle
  - export NINJA_PATH=/usr/bin/ninja
  - export PATH=`echo $ANDROID_HOME/cmake/*/bin`:`echo $ANDROID_HOME/build-tools/*`:$PATH
  - echo -e "APP_ID = ${APP_ID}\nAPP_HASH = ${APP_HASH}" > API_KEYS
script:
  # If some stage fails, exit inmediatly
  - set -e
  # Prebuild
  - "cd TMessagesProj/jni"
  - "./build_ffmpeg_clang.sh"
  - "./patch_ffmpeg.sh"
  - "./patch_boringssl.sh"
  - "./build_boringssl.sh"
  - "cd ../.."
  # Build
  - "./gradlew assembleAfatRelease"
  - "rm API_KEYS"

before_deploy:
  - zipalign -v -p 4 ./TMessagesProj/build/outputs/apk/afat/release/TMessagesProj-afat-release-unsigned.apk TF-BETA-THERMATK-${TRAVIS_TAG}.apk
  # - apksigner sign --ks my-release-key.jks --out TF-BETA-THERMATK-${TRAVIS_TAG}.apk TMessagesProj-afat-release-unsigned-aligned.apk
deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file: "TF-BETA-THERMATK-${TRAVIS_TAG}.apk"
  skip_cleanup: true
  on:
    tags: true
